### ISSUE TITLE
Update needed for org.codehaus.plexus artifacts

### ISSUE THREAD

**Issue by AndreVirtimo** [ops4j/org.ops4j.pax.url#425]
Hello,

I'm not really sure if this project is affected. Maybe it is a false positive CPE match. The information on the CVE and the following links are very limited.

Our scanning tools detected vulnerable dependencies.

* pax-url-aether-2.6.14.jar (shaded: org.codehaus.plexus:plexus-cipher:2.0)
* pax-url-aether-2.6.14.jar (shaded: org.codehaus.plexus:plexus-interpolation:1.26) 

Both with https://nvd.nist.gov/vuln/detail/CVE-2022-4244 and https://nvd.nist.gov/vuln/detail/CVE-2022-4245 .

**Comment by grgrzybek** [comment]
CVE-2022-4244 is fixed by https://github.com/codehaus-plexus/plexus-utils/commit/33a2853df8185b4519b1b8bfae284f03392618ef and pax-url-aether doesn't use `org.codehaus.plexus.util.Expand` class (at least not at runtime - it may be used at build time during normal Maven build)

CVE-2022-4245 is about `org.codehaus.plexus.util.xml.XmlWriterUtil#writeComment()` and pax-url-aether, while using plexus-cipher which may reference plexus-utils, uses only the code that's responsible for decrypting maven password and master password.

Thanks for report anyway ;)

**Comment by AndreVirtimo** [comment]
Thank you for the clarification.
